cmake/ecbuild_try_run.cmake

Set LINK_LIBRARIES to CMAKE_EXE_LINKER_FLAGS (if set) in ecbuild_try_run.  Setting of e.g. rpath in CMAKE_EXE_LINKER_FLAGS may be necessary for an executable to run; this allows such settings to be passed to the compilation of the test executable.

Set LINK_LIBRARIES for try_run to CMAKE_EXE_LINKER_FLAGS

---

cmake/FindProj4.cmake

On Windows we install proj4 from conda. The proj4 v6 package doesn't
contain proj.lib - instead it has proj_6_0.lib. This change allows ECMWF
cmake packages to find proj4 v6 on Windows.
See https://github.com/conda-forge/magics-feedstock/pull/35 for motivation.

Search for proj_6_0.lib if proj.lib isn't found

---

cmake/ecbuild_add_test.cmake

This commit allows users to specify the path to the windows testing
bashrc for their project instead of assuming where the file will be
found.

Windows: fix path to windows testing bashrc

---

cmake/ecbuild_generate_project_config.cmake

In `ecbuild_generate_project_config()`, `PATH_VARS` parameters must be accessed via `_PAR_PATH_VARS` name.

Fix: PATH_VARS unused in ecbuild_generate_project_config()

---

cmake/ecbuild_bundle.cmake
cmake/ecbuild_git.cmake

For some time now, [JCSDA](https://github.com/jcsda) has been forking third-party repositories. If there are git submodules employed by a repository that is used/co-developed, those submodules have to be forked as well.  Examples (relevant to JCSDA) are `mom6` and it's dependencies e.g. `CVmix`, `geoKdtree`, `mom6-da-hooks` and now `ocean_bgc`.
This adds burden on  the developer to maintain the `ecbuild` layer on these submodules as well as keeping them in sync; i.e. keep a track of the `SHA` in the submodules.
With this option `RECURSIVE`, one can recursively clone/update these via the `ecbuild_bundle`, this makes the job much easier and allows us to obtain the appropriate `SHA` of these dependencies as they relate to the upstream repository.  The appropriate git call `git submodule …

allow ecbuild_git to checkout git submodules

---

cmake/ecbuild_declare_project.cmake
cmake/ecbuild_define_options.cmake

For projects in Git repositories, ecbuild generates variables recording the hash of the git revision at the time of the last build. This is no doubt useful in production, but it is awkward during development, since it causes CMake to be re-run after each Git commit, which can be time-consuming for large projects. This PR adds an option to disable generation of these variables.
As things stand, this option is not marked as advanced, but I'm happy to mark it as such.

Make generation of the *_GIT_SHA1 variables optional

---

cmake/ecbuild_remove_fortran_flags.cmake

The function `ecbuild_remove_fortran_flags()` uses an incorrect REGEX to remove flags from the Fortran_FLAGS variables.  Specifying flag `-g` will remove the leading `-g` from any flag that starts that way.  e.g., the intel flag `-gcc-name=gcc-9.3.0` -> `cc-name=gcc-9.3.0` -> *BOOM*.
This PR fixes the regex to preserve all other flags except the exact matched flag.
Test script for improved REGEX.
```
function(stripflags flag str)
string(REGEX REPLACE "(^|[ ]+)${flag}($|[ ]+)" "\\1" out "${str}")
message("REPLACE FLAG:${flag} Transform: \"${str}\" -> \"${out}\"")
endfunction()
set(flag "-g")
set(tests "-g" " -g" "-g " "-g -foo" "-bar -g -baz" "-ggg -g -gcc -g" "-gcc" "--g -g-" "---g" "   -g" "-g   " "   -g   " "-g-g")
foreach( t IN LISTS tests)
stripflags(${flag} "${t}")
endforeach()
``` …

ecbuild_remove_fortran_flags() uses incorrect REGEX

---

cmake/FindNetCDF.cmake

This version of FindNetCDF.cmake uses the `nc-config`, `nf-config` and `ncxx4-config` to set the appropriate paths and flags for linking against the various NetCDF language components.  This allows linking against static NetCDF installs, and linking on systems where each language component is installed to a separate prefix (as occurs in some HPC environment module based systems). The current FindNetCDF.cmake does not work for these scenarios.
In order to ensure the user links against the namespaced imported interface targets `NetCDF::NetCDF_<LANG>` targets, we have deprecated the `NetCDF_LIBRARIES` variable, but it should still work for packages already using that variable.  It now points to the imported interface targets for each searched component.

Improved FindNetCDF.cmake

---

cmake/FindNetCDF.cmake

This is a hopefully clearer explanation of my proposed fix for https://github.com/ecmwf/ecbuild/issues/46.  It ensures that component specific paths for NetCDF libraries are searched as well as for the includes; currently only the non component specific paths are searched for libraries.

Search component specific paths for NetCDF libraries as well as includes

---

cmake/FindNetCDF.cmake

The library name for the NetCDF::NetCDF_CXX target with `brew install netcdf-cxx` now contains netcdf-cxx4 instead of netcdf_c++4.
This could be due to a different CMake build system being used.

Fix detection of NetCDF::NetCDF_CXX with more recent installations

---

cmake/ecbuild_project.cmake

This avoids following warning for each project configured with cmake 3.27 onwards:
```
CMake Deprecation Warning at /home/runner/work/_temp/install/ecbuild/share/ecbuild/cmake/ecbuild_project.cmake:44 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
CMakeLists.txt:24 (project)
```

Avoid warning of deprecated cmake 3.5 by removing mention of cmake 3.3

---

cmake/fortran_features/finalization.F90

Resolves #62.  The LOC intrinsic is only used for some write statements, so it looks like it can be cpp'ed out for NAG.  I can do something more sophisticated if desired, but this change results in this ecbuild output:
-- Checking Fortran support for "finalization"
-- Checking Fortran support for "finalization" -- works
-- Feature FINAL enabled
-- FCKIT_HAVE_FINAL [1]
--   FCKIT_FINAL_FUNCTION_RESULT              = 1
--   FCKIT_FINAL_UNINITIALIZED_LOCAL          = 0
--   FCKIT_FINAL_UNINITIALIZED_INTENT_OUT     = 1
--   FCKIT_FINAL_UNINITIALIZED_INTENT_INOUT   = 0
--   FCKIT_FINAL_NOT_PROPAGATING              = 0
--   FCKIT_FINAL_NOT_INHERITING               = 0
--   FCKIT_FINAL_BROKEN_FOR_ALLOCATABLE_ARRAY = 0
--   FCKIT_FINAL_BROKEN_FOR_AUTOMATIC_ARRAY   = 0

CPP out LOC calls for NAG.

---

cmake/fortran_features/CheckFortranFeatures.cmake

`ecbuild_check_fortran` triggers  a string match for `"_fail"` against a filename held in ecbuild, which can cause an unintended match if the path to the ecbuild installation contains this string. This is easily done in an IFS build if the branch name contains this string, because the cloned ecbuild will sit inside a directory named after the IFS branch, e.g. `.../user_cycle_fix_failures/source/ecbuild/...`
The result is that any Fortran feature being checked for is accidentally removed from the list of features to check, resulting in an empty feature list and an instant build failure:
`  CRITICAL - [Fortran] Expected to find only one feature.  Found 0 --`
Making the match condition stricter against the files it's actually looking for solves the problem.

Stricter match condition for _fail strings

---

cmake/ecbuild_features.cmake

This fixes an issue introduced with #69 where features that are ON by default, but then disabled according to run-time criteria such as unavailable libraries, are mistakenly reported as being enabled. This becomes problematic when one package queries another package's CMake options in order to modify its own behaviour (in this case, it was Metview querying the options of mars-client).

Fix ecbuild_disable_unused_feature

---

cmake/ecbuild_add_option.cmake

If a `<project>_ENABLE_<feature>` variable is used, it's not directly referenced in the ecbuild.log output unless both that _and_ `ENABLE_<feature>` are present (which triggers a warning). If only the project-specific variable is present and it differs from the default setting, the output can be confusing; for example, if we have `ECCODES_ENABLE_NETCDF=OFF`:
```
eccodes - DEBUG - ecbuild_add_option(NETCDF): defaults to ON
eccodes - DEBUG - ecbuild_evaluate_dynamic_condition(_NETCDF_condition): checking condition '' -> TRUE
eccodes - DEBUG - ecbuild_add_option(NETCDF): ENABLE_NETCDF not found in cache
eccodes - DEBUG - ecbuild_add_option(NETCDF): defining option ENABLE_NETCDF 'Support for GRIB to NetCDF conversion' ON
eccodes - DEBUG - ecbuild_add_option(NETCDF): ENABLE_NETCDF=ON
eccodes - …
```

Add log output when overriding a global option setting

---

cmake/ecbuild_define_build_types.cmake

Closes #33 
As stated in #33, our group (who are 'mild' users of ecbuild; we like some of your macros), have our own set of `CMAKE_BUILD_TYPE`: `Debug`, `Release`, and `Aggressive`. That last one, of course, isn't recognized by ecbuild.
For a while, we've been maintaining a fork and at this point, the only difference is [code in `cmake/ecbuild_define_build_types.cmake`](https://github.com/ecmwf/ecbuild/compare/develop...GEOS-ESM:ecbuild:geos/develop) to make `Aggressive` allowed.
In #33, @wdeconinck suggested perhaps relaxing from `ecbuild_critical` to `ecbuild_warn`. I've done this here and tried to make the warning informative, e.g.:
```
CMake Warning at @cmake/@ecbuild/cmake/ecbuild_log.cmake:162 (message):
WARN - CMAKE_BUILD_TYPE is not recognized.  Build type options defined
by …
```

Use warning for unknown build type

---

cmake/ecbuild_add_c_flags.cmake
cmake/ecbuild_add_cxx_flags.cmake
cmake/ecbuild_add_fortran_flags.cmake
cmake/ecbuild_add_lang_flags.cmake
examples/fortran-compile-options/CMakeLists.txt
examples/fortran-compile-options/main.F90

In more recent CMake the COMPILE_FLAGS property on targets is deprecated in favour of the COMPILE_OPTIONS property. This COMPILE_OPTIONS property can be set on targets using
```
target_compile_options(my_target PUBLIC -foption1 -foption2)
```
or
```
target_compile_options(my_target PUBLIC -foption1;-foption2)
```
Important to note is that the COMPILE_OPTIONS is a cmake LIST.
Currently the signature of functions `ecbuild_add_fortran_flags`, `ecbuild_add_c_flags`, `ecbuild_add_cxx_flags` were expecting that the flags were given as a space-separated string, and not a LIST.
This PR tries to also allow a LIST argument for the flags to be more flexible and interoperate better with the more modern COMPILE_OPTIONS.

Allow ecbuild_add_<lang>_flags with a  LIST argument

---

tests/project_summary/configure.sh
tests/project_summary/test_project/CMakeLists.txt

The new tests prove that issue https://github.com/ecmwf/ecbuild/issues/73 is fixed by the changes intended to correct https://github.com/ecmwf/ecbuild/issues/79.

Test to demonstrate option with REQUIRED_PACKAGES displays status correctly

---

tests/ecbuild_add_option/build-and-run.sh
tests/ecbuild_add_option/test_project/CMakeLists.txt

This particular test failed when running with CMake 4.x, and some of the OLD policies have been effectively removed.
Since ecbuild now requires the use of CMake 3.18 it no longer makes sense to keep tests that require compatibility with CMake 2.x.
Note: this is a quick fix to prevent this particular test from failing, but a more overall update is required to remove the unnecessary code dealing with CMake 2.x compatibility.
This resolves issue #97.

Remove ECBUILD_2_COMPAT related test

---

cmake/ecbuild_compile_options.cmake

This updates ecbuild_compile_options.cmake to handle the NAG compiler.

Handle NAG compiler

---

cmake/ecbuild_install_project.cmake

When a feature is enabled, it is expected that the values of `<package>_HAVE_<feature>` are set to `1` instead of `True`.
The same should then hold for automatically exported variables during `ecbuild_install_project`.

Fix expected value of project_HAVE_feature in exports

---

tests/ecbuild_find_python/configure.sh

Remove module load python3 from ecbuild_test_python script.  Addresses #109.
I don't know why the module load is needed.  The very next line tests that python3 is in $PATH and runs.  Why does it matter if it is loaded via a module or not?
By opening this pull request, I affirm the following:
* All authors agree to the [Contributor License Agreement](https://github.com/ecmwf/codex/blob/main/Legal/contributor_license_agreement.md).
* The code follows the project's coding standards.
* I have performed self-review and added comments where needed.
* I have added or updated tests to verify that my changes are effective and functional.
* I have run all existing tests and confirmed they pass.

Remove module load python3
